name: "Terraform"

on:
  # Uncomment to enable staging deploy from main
  push:
    branches:
      - main
  release:
    types: [published]
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGION: us-east-1 
    defaults:
      run:
        working-directory: tf_files
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
        region: us-east-1 
        # role-to-assume: arn:aws:iam::123456789100:role/my-github-actions-role
        

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          # terraform_version: 1.0.1
          terraform_wrapper: false

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check 
        continue-on-error: true 

      - name: Terraform Init
        id: init
        run: terraform init